### ISSUE TITLE
Ground station compilation problem

### ISSUE THREAD

**Issue by G1246830895** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#36]
When I put the ground station into the ROS workspace and compile it, the following problems occurred:
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
   Could not find a package configuration file provided by "uav_utils" with
   any of the following names:

     uav_utilsConfig.cmake
     uav_utils-config.cmake

   Add the installation prefix of "uav_utils" to CMAKE_PREFIX_PATH or set
   "uav_utils_DIR" to a directory containing one of the above files. If
   "uav_utils" provides a separate development package or SDK, be sure it has
   been installed.
Call Stack (most recent call first):
   joy_ctrl/CMakeLists.txt:6 (find_package)
How can I solve this problem?

**Comment by bigsuperZZZX** [comment]
Have you compiled your code with folder "[utils](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/tree/master/utils)"?
Package "uav_utils" lies in "[utils](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/tree/master/utils)" folder, which contains many packages needed by the whole system.
Remember to copy this folder to both the onboard computer and the ground station.

**Comment by G1246830895** [comment]
I downloaded the source code directly from github, and then copied the "ground station" folder to the "src" folder of catkin_ws. I run catkin_make and I get the above error. What should I do to solve this problem?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bigsuperZZZX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 中午1:55
收件人:&nbsp;"HKUST-Aerial-Robotics/Teach-Repeat-Replan"<Teach-Repeat-Replan@noreply.github.com&gt;;
抄送:&nbsp;"梓晨"<1246830895@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HKUST-Aerial-Robotics/Teach-Repeat-Replan] Ground station compilation problem (#36)





 
Have you compiled your code with folder "utils"?
 Package "uav_utils" lies in "utils" folder, which contains many packages needed by the whole system.
 Remember to copy this folder to both the onboard computer and the ground station.

**Comment by bigsuperZZZX** [comment]
Just copy the "utils" folder to the same directory of "ground station" and run "catkin_make -j1".
Like this:
![image](https://user-images.githubusercontent.com/26641182/85980182-7e578a80-ba14-11ea-95e1-872cbdba3d8a.png)

**Comment by G1246830895** [comment]
I will try now

**Comment by G1246830895** [comment]
ground_station/joy_ctrl/CMakeLists.txt:6 (find_package)


-- Could not find the required component 'uav_utils'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "uav_utils" with
  any of the following names:

    uav_utilsConfig.cmake
    uav_utils-config.cmake

  Add the installation prefix of "uav_utils" to CMAKE_PREFIX_PATH or set
  "uav_utils_DIR" to a directory containing one of the above files.  If
  "uav_utils" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ground_station/joy_ctrl/CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/gzh/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/gzh/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
it don't work.

**Comment by G1246830895** [comment]
I can't directly copy "utils" to src, otherwise there will be a file with the same name, which can't execute catkin_make. I copied the "utils" file in "ground station" to src and deleted the file in "ground station". I run catkin_make -j1 and the error still exists.

**Comment by G1246830895** [comment]
I also manipulated every folder like this, but it still doesn't work

**Comment by bigsuperZZZX** [comment]
Try to place the folders like my workspace.
![1](https://user-images.githubusercontent.com/26641182/85981693-3a19b980-ba17-11ea-8a4e-58d468fdd27f.png)
![2](https://user-images.githubusercontent.com/26641182/85981699-3c7c1380-ba17-11ea-80d2-ef871339319c.png)

And before re-building, delete the "devel/" and "build/" folders.

**Comment by G1246830895** [comment]
i'll try like this.

**Comment by G1246830895** [comment]
Should the other folders be in files?

**Comment by G1246830895** [comment]
Should the other folders be placed in the "files" folder?

**Comment by bigsuperZZZX** [comment]
Don't need to.
"files" folder is the folder in [github repo](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/tree/master/files) and only some pictures in it. But it was needed by "key2joy.py", so don't delete it.

**Comment by G1246830895** [comment]
Did you delete the problematic folders? When I keep "joy_ctrl", the compilation still gives an error. This error is consistent with the error when I first compiled "utils" when compiling "Ground Station"

**Comment by G1246830895** [comment]
Will this cause problems for subsequent incomplete functions?

**Comment by bigsuperZZZX** [comment]
Yes, it will cause problems.
Which branch are you use, master or experiment? If you use master branch, No need to change any folders or files, just put all the foldes in to a "src" folder and  type "catkin_make -j1" will be totally ok. Of course the needed solvers and other softwares shouled be installed properly in advance. The steps are listed in readme.md in detial.
And which ros version are you use? We only tested the code in kinetic but with various platforms.
Maybe re-create a blank workspace and put the files there and re-build the workspace will be ok? It sounds like you have already  modified some folders.

**Comment by G1246830895** [comment]
I use the experimental part. I just created a blank workspace and then followed the steps of readme. I encountered these problems when I compiled the code of the ground station. Is there a better solution? We will conduct a real machine test at that time

**Comment by G1246830895** [comment]
I use ubuntu16.04 OS and install ros-kinetic.

**Comment by bigsuperZZZX** [comment]
I checked the code and found that a bug which causes the problem.
This happened due to git commands ignore blank folders which is required by CMake.
Now the bug has been fixed, you can download the repo again and it should works ok.

**Comment by G1246830895** [comment]
I downloaded the code again.When I compile according to the following operation method, the problem still exists.
![image](https://user-images.githubusercontent.com/48216024/86005424-3aca4400-ba47-11ea-852f-da66c67a220e.png)
When I operate as I did, the result is as follows
![image](https://user-images.githubusercontent.com/48216024/86005747-97c5fa00-ba47-11ea-9536-1ddc84018086.png)
![image](https://user-images.githubusercontent.com/48216024/86005780-a3192580-ba47-11ea-84ea-38207a3ac429.png)

**Comment by G1246830895** [comment]
I deleted the "joy_ctrl" folder and the compilation was successful.

**Comment by bigsuperZZZX** [comment]
I just found that I missed another error in that CMakelists.txt file and I have fixed it I think.
If the "joy_ctrl" package gets messing, you will not be able to perform "manual teach". If you do not need that function, deleting is ok.

**Comment by G1246830895** [comment]
I think I need this function. Can this error be fixed? If this error cannot be fixed, how can I implement the teaching function?

**Comment by bigsuperZZZX** [comment]
I have already fixed the bug and have just successfully compiled the latest version. Try it, and remember to use "catkin_make -j1".

**Comment by G1246830895** [comment]
how did you do it? I just re-downloaded the compilation and the error still exists. Can you elaborate on your operation process?

**Comment by G1246830895** [comment]
When I deleted the "joy_ctrl" folder, the compilation was successful again.

**Comment by bigsuperZZZX** [comment]
Is your "ground_station/joy_ctrl/CMakeLists.txt" look like this?
![image](https://user-images.githubusercontent.com/26641182/86078235-3db54b00-bac0-11ea-96cc-12ffcb1a1f4d.png)

The steps are:
1. Copying the files in "ground_station/" to a ros workspace src/ folder. 
2. Execute "catkin_make -j1".

**Comment by G1246830895** [comment]
![image](https://user-images.githubusercontent.com/48216024/86079433-0bf1b380-bac3-11ea-8117-5cda6747f07f.png)
My steps are as follows:
1.Copying the files in "ground_station/" to a ros workspace src/ folder.
2.Execute "catkin_make -j1".
Is it possible for this reason: when I run install_tools.sh,
sudo update-alternatives --install -y /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5 &
sudo update-alternatives --install -y /usr/bin/gcc gcc /usr/bin/gcc-7 50 --slave /usr/bin/g++ g++ /usr/bin/g++-7
These two instructions will prompt me that the priority must be an integer

**Comment by Hyuhao** [comment]
I think I have fixed this problem. You need to add the following commands in the package.xml file under the joy_ctrl folder

- <build_depend>uav_utils </build_depend> 

- <run_depend>uav_utils </run_depend>

**Comment by G1246830895** [comment]
This problem has been solved, thank you very much
